In [1]:
print("Hello, World!")

Hello, World!


In [6]:
name = input("What is your name?")
print("Hello", name)

What is your name? yashika


Hello yashika


In [8]:
name = input("What is your name?")
print("I LIKE CAPITAL LETTER", name.upper())

What is your name? riya


I LIKE CAPITAL LETTER RIYA


In [12]:
kg = float(input("Enter the weight in kilogram: "))
lbs = kg*2.2046
print(f"The {kg} kilogram to lbs is: {lbs}")

Enter the weight in kilogram:  5


The 5.0 kilogram to lbs is: 11.023


In [18]:
radius = float(input("Enter the radius: "))
pi = 3.14
c = 2*pi*radius
print(f"The circumference of the circle is: ", c)

Enter the radius:  5


The circumference of the circle is:  31.400000000000002


In [30]:
a = 7
a = a * 3
a = a + 6
a = a // 3
number = a - 7

In [32]:
number

2

In [40]:
a = int(input("Enter a value: "))
b = int(input("Enter another value: "))
print(f"The product of a and b is:", a*b)

Enter a value:  2
Enter another value:  3


The product of a and b is: 6


In [1]:
a = int(input('Enter the year:'))
days = a*365
hours = days*24
minutes = hours*60
seconds = minutes *60
print(f'The days {days}, hours {hours}, minutes {minutes} and seconds {seconds} has passed since you were born.')

Enter the year: 2000


The days 730000, hours 17520000, minutes 1051200000 and seconds 63072000000 has passed since you were born.


In [44]:
price = int(input("Enter the price:"))
percentage_tip = int(input("Enter the tip:"))
tip = price * percentage_tip/100
round(tip, 2)
print(tip)

Enter the price: 150
Enter the tip: 20


30.0


In [1]:
hours = float(input("Enter the hours: "))
rate = float(input("Enter the rate: "))
groce_pay = rate * hours
print(f"The groce_pay is: ", int(groce_pay))

Enter the hours:  3.5
Enter the rate:  400


The groce_pay is:  1400


In [3]:
hours = float(input("Enter the hours: "))
rate = float(input("Enter the rate: "))
pay = hours * rate
if(hours > 40):
 groce_pay = 40 * rate + (hours-40) * 1.5 * rate
else:
    pay
print(int(groce_pay))

Enter the hours:  45
Enter the rate:  10


475


In [30]:
market_price = float(input("Enter the current market_price: "))
gender = input("Enter your gender: ")
if(gender == "male"):
    age = int(input("Enter your age: "))
    if(age<=26):
        yearly_price = 0.23 * market_price
        print(yearly_price)
    else:
        yearly_price = 0.09 * market_price
        print(yearly_price)
elif(gender == "female"):
    car_type = input("Enter the car type: ")
    if(car_type == "sport car"):
        yearly_price = 0.21 * market_price
        print(yearly_price)
    else:
        yearly_price = 0.1 * market_price
        print(yearly_price)
else: 
    print("Wrong Format")

Enter the current market_price:  1000
Enter your gender:  female
Enter the car type:  sport car


210.0


In [42]:
smallest_so_far = 23
print("before: ", smallest_so_far)
for new_num in (9, 41, 12, 3, 74, 25):
    if(new_num < smallest_so_far):
        smallest_so_far = new_num
        print(smallest_so_far, new_num)

print("After: ", smallest_so_far)

before:  23
9 9
3 3
After:  3


In [53]:
zork = 0
print("before: ", zork)
for thing in (9, 41,12, 3, 74, 25):
     zork = zork + thing 
print("thing", zork) 


before:  0
thing 164


In [27]:
#Rewrite your pay computation with time-and-a-half for overtime and create a function called compute pay which takes two parameters (hours and rate)
def computepay(hours, rate):
    if(hours > 40):
        groce_pay = 40 * rate + (hours-40) * 1.5 * rate
        print(groce_pay)
    else:
        groce_pay = hours * rate
        print(groce_pay)
computepay(45, 10)

475.0


In [42]:
import random
list = ['father', 'enterprise', 'science', 'programming', 'resistance', 'fiction', 'condition', 'reverse', 'computer', 'python']
word = random.choice(list)
print(word)
jumbled = random.sample(word, len(word))
print("The jumbled word is:", jumbled)
guess = input("enter the guessed word:")
if guess == word:
    print("Correct guess")
else:
    print("wrong guess")


fiction
The jumbled word is: ['f', 'c', 'n', 'i', 'i', 'o', 't']


enter the guessed word: fiction


Correct guess


In [7]:
def fibonacci_series(n):
    if n == 1:
        return [0]
    if n == 2:
        return [0, 1]

    f1 = 0
    f2 = 1
    f_series = []
    for i in range(2,5):
        next_f = f1 + f2  
        f_series.append(next_f)  
        f1 = f2  
        f2 = next_f  
    print(f_series)
fibonacci_series(6)

[1, 2, 3]


In [37]:
import random

choice = ['rock', 'paper', 'scissor']
computer_choice = random.choice(choice)
print("Computer choice:", computer_choice)

user_choice = input("Enter your choice (rock, paper or scissor):")

if user_choice not in choice:  
    print("It's an invalid choice")  
else:  
    if user_choice == computer_choice:  
        print("It's a tie")  
    elif (user_choice == 'rock' and computer_choice == 'scissor') or \
         (user_choice == 'scissor' and computer_choice == 'paper') or \
         (user_choice == 'paper' and computer_choice == 'rock'):  
        print("The computer lost")  
    else:  
        print("The computer won")

Computer choice: paper


Enter your choice (rock, paper or scissor): scissor


The computer lost


In [69]:
fruit = 'pineapple'
for i in range(len(fruit)):
    print(f"{i}, {fruit[i]}")

0, p
1, i
2, n
3, e
4, a
5, p
6, p
7, l
8, e


In [73]:
a ='star'
dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri

In [75]:
a.upper()

'STAR'

In [89]:
a= 'stars are shining today'
a.capitalize()

'Stars are shining today'

In [91]:
a.title()

'Stars Are Shining Today'

In [93]:
a.replace('shining', 'dull')

'stars are dull today'

In [111]:
a = '   stars shine   '
a.lstrip()

'stars shine'

In [129]:
a = '   stars shine   '
a.rstrip()

'   stars shine'

In [ ]:
a = 'From stephen.marquard@uct.ac.za Sat Jan 5 09:14:16 2008'
index = a.find('@')
domain = a[index:]
end = domain.find(' ')
while end != -1:
    domain = domain[:end]
print(domain)

In [180]:
a = 'From stephen.marquard@uct.ac.za Sat Jan 5 09:14:16 2008'  
index = a.find('@')  
domain = a[index+1:]  # Get the substring starting from '@'  
end_index = domain.find(' ')  
if end_index != -1:  
    domain = domain[:end_index]  
print(domain)

uct.ac.za


In [11]:
b = ('a',) #single tuple creation
c = ('d')
type(c), type(b)

(str, tuple)

In [15]:
a = 20
b = 30
(a, b) =(b, a)
print(a, b)

30 20


In [ ]:
list = input("Enter the list elements: ").split(',')
tuple = tuple(list.strip() for elements in list)

user_choice = input("Enter the choice of user")
if user_choice in tuple:
    print(f"{user_choice} is present in tuple:")
else:
    print(f"{user_choice} is present:")

In [ ]:
#Write a program to add an element to tuple based on the user given value in a specifix index, 

In [1]:
#Create class
class Employee:
    pass 
#create instance of the class
emp_1 = Employee()
#Take input
name = input("Enter your name: ")
#Assign name to the first instance
emp_1.name = name
#Assign salary to the first instance
emp_1.salary = 35000
#Print
print(emp_1.name)
print(emp_1.salary)

Enter your name:  



35000


In [3]:
type(emp_1)

__main__.Employee

In [7]:
#Self
class Manager:
    def __init__(self, name, department, salary):
        self.name = name
        self.department = department
        self.salary = salary

name = input("Enter your name: ")
department = input("Enter department name: ")
salary = int(input("Enter Salary: "))
#Create object of the class
manager_1 = Manager(name, department, salary)
print(manager_1.name)
print(manager_1.department)
print(manager_1.salary)

Enter your name:  yashika
Enter department name:  m.tech
Enter Salary:  2000


yashika
m.tech
2000


In [9]:
class Car:
    def setName(self, name):
        self.name = name
    def getName(self):
        return self.name

Honda = Car()
carname = input("Enter car name: ")
Honda.setName(carname)
print("Name of the car is: ", Honda.getName())

Enter car name:  jazz


Name of the car is:  jazz


In [21]:
class Student:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
name = input("Enter name of student1: ")
age = int(input("Enter age of student1: "))
Student1 = Student(name, age)
print(Student1.name)
print(Student1.age)
name = input("Enter name of student2: ")
age = int(input("Enter age of student2: "))
Student2 = Student(name, age)
print(Student2.name)
print(Student2.age)

Enter the name:  yash
Enter your age:  20


yash
20


Enter the name:  riya
Enter your age:  19


riya
19


In [23]:
class ShoppingCart:
    def __init__(self):
        self.items = []  
     
    def add_item(self, item, price):
        self.items.append((item, price))
        
    def remove_item(self, item):
        for cart_item in self.items:
            if cart_item[0] == item:
                self.items.remove(cart_item)
                print(f"{item} removed from the cart.")
                return
        print(f"Item '{item}' not found in the cart.")

    def total_price(self):
        total = 0
        if cart_item in self.items:
            for item, price in self.items:
                total += price
            return total
        else:
            print("The cart is empty.")

    def display_items(self):
        if self.items:
            print("Current items in cart:")
            for item, price in self.items:
                print(f"{item} - {price}")
        else:
            print("Cart is empty.")
    
cart = ShoppingCart()
cart.add_item("Orange", 100)
cart.add_item("Lemon", 10)
cart.add_item("Apple", 50)
cart.add_item("Watermelon", 30)

cart.display_items()
cart.remove_item("Orange")
cart.display_items()

print(f"Total price: {cart.total_price()}")


Current items in cart:
Orange - 100
Lemon - 10
Apple - 50
Watermelon - 30
Orange removed from the cart.
Current items in cart:
Lemon - 10
Apple - 50
Watermelon - 30
Total price: 90


In [19]:
#Exception handling
try:
    a = int(input("Enter the number(a): "))
    b = int(input("Enter the number(b): "))
    div = a/b
    print(div)
except:
    print("kindly enter non zero value of b")

Enter the number(a):  10
Enter the number(b):  0


kindly enter non zero value of b


In [21]:
a = int(input("Enter the number(a): "))
b = int(input("Enter the number(b): "))
div = a/b
print(div)

Enter the number(a):  10
Enter the number(b):  0


ZeroDivisionError: division by zero

In [1]:
#Exception handling
try:
    a = int(input("Enter the number(a): "))
    b = int(input("Enter the number(b): "))
    div = a/b
    print(div)
except ZeroDivisionError:
    print("kindly enter non zero value of b")
except ValueError:
    print("Invalid input kindly enter integer value")

Enter the number(a):  FOUR


Invalid input kindly enter integer value


In [9]:
#Write program that repeatedly asks for a whole number input, handling exceptions and allowing users to retry or exit based on their choices.
#Firstly, used a while loop to keep prompting the user until they enter a valid whole number. Inside the loop, used a try block to attempt to convert
#the user's input to an integer. If the conversion raises a ValueError, print "you must enter a whole number!" and proceed to ask if the user wants to 
#try again (y/n)?. If the user enters "y" (yes), the program should continue the loop. If the user enters "n" (no), or if they enter anything other than
#"y", the program should print "ok, see you next time!" and exit the loop. If the user interrupts the program with a keyboard interrupt (CTRL+C), catch 
#the KeyboardInterrupt exception, print "You pressed Ctrl+C! See you next time!" and exit the loop.

def whole_number():
    while True:
        try:
            user_input = input("Enter a whole number: ")
            number = int(user_input)
            print("you enter the whole number")
        except ValueError:
            print("you must enter a whole number!")
            try:
                b = input("Enter your choice (y/n)? ")
                if b == "y":
                    print("Let's try again:")
                    continue
                else:
                    print("ok, see you next time!")
                    return
            except KeyboardInterrupt:
                print("You pressed Ctrl+C! See you next time!")

whole_number()

Enter a whole number:  09


you enter the whole number


Enter a whole number:  -3


you enter the whole number


Enter a whole number:  4.5\


you must enter a whole number!


Enter your choice (y/n)?  n


ok, see you next time!


In [19]:
while True:
    try:
        user_input = input("Enter a whole number: ")
        number = int(user_input)
        print("you enter the whole number")
    except ValueError:
        print("you must enter a whole number!")
        try:
            b = input("Enter your choice (y/n)? ")
            if b == "y":
                print("Let's try again:")
                continue
            else:
                print("ok, see you next time!")
                break
                    
        except KeyboardInterrupt:
            print("You pressed Ctrl+C! See you next time!")

Enter a whole number:  10


you enter the whole number


Enter a whole number:  5


you enter the whole number


Enter a whole number:  0.4


you must enter a whole number!


Enter your choice (y/n)?  n


ok, see you next time!


In [21]:
try:
    age = int(input("Enter your age"))
    if age < 0:
        raise ValueError("Age cannot be negative")
    print(f"Age when doubled {age * 2}")
except ValueError:
    print("Age cannot be less than zero")
finally:
    print("Excecuted in any condition")

Enter your age -6


Age cannot be less than zero
Excecuted in any condition


In [3]:
class OurException(Exception):  
    def __init__(self, message):  
        super().__init__(message)  
        self.message = message  

class UsingUserException:  
    def __init__(self):  
        try:  
            a = int(input("Enter value of a: "))  
            b = int(input("Enter value of b: "))  
            if b == 0:  
                raise OurException("b should be greater than zero")  
            d = a / b  
            print(f"Division operation successful: {d}")  
        except OurException as err:  
            print("Raised a user-defined exception:", err.message)  

# Create an instance to execute the logic  
UsingUserException() 

Enter value of a:  4
Enter value of b:  2


Division operation successful: 2.0


In [5]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [9]:
#Creating 0d array
arr0 = np.array(50)
print("0D array is ", arr0)
# 1d array
arr1 = np.array([1,2,3,4]) #In 1d array we use 0d array elements as list
print("!D array is ", arr1)
# 2d array
arr2 = np.array([[1,1,1],[2,3,4]]) #In 2d array we pass 1d array as elements
print("2D array is ", arr2)
#3d array
arr3 = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]]) #In 3d array we pass 2d array as elements
print("3D array is ", arr3)

0D array is  50
!D array is  [1 2 3 4]
2D array is  [[1 1 1]
 [2 3 4]]
3D array is  [[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]


In [27]:
arr0 = np.array(1)
print("A 0D array is:", a0)
arr1 = np.array([1,2,3,4]) 
print("A 1D array with elements:", arr1)
arr2 = np.array([[1,1,1],[1,2,1]]) 
print("A 2D array with elements:", arr2)
arr3 = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]]) 
print("A 3D array with elements:", arr3)

A 0D array is: 1
A 1D array with elements: [1 2 3 4]
A 2D array with elements: [[1 1 1]
 [1 2 1]]
A 3D array with elements: [[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]


In [15]:
#Attributes of ndarray: 1. ndarray.ndim, 2. ndarray.shape, 3. ndarray.size, 4. ndarray.dtype, 5. ndarray.itemsize, 6. ndarray.data

In [39]:
import numpy as np  
print("Od array:", arr0.ndim)
print("1d array:", arr1.shape)
print("2d array:", arr2.size)
print("3d array:", arr3.dtype)
print("3d array:", arr3.shape)

Od array: 0
1d array: (4,)
2d array: 6
3d array: int32
3d array: (2, 2, 3)


In [41]:
#ndarray.reshape: It is used to reshape the current elements of an array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr = arr.reshape(4,3)
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [43]:
#ndarray.flatten: It returns the copy of the array flattened into a 1D array
new1D = new_arr.flatten()
new1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
#ndarray.transpose: swap the row and columns in the array
new = new_arr.transpose()
new

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [59]:
#temperatures = [75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8] Steps to perform:
#1. Explore the key attributes of Numpy arrays, including ndim, shape, size, dtype, itemsize, and data
import numpy as np
temp = np.array([75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8])
print("Number of Dimensions:", temp.ndim)
print("Shape:", temp.shape)
print("Size:", temp.size)
print("Data Type:", temp.dtype)
print("Item Size:", temp.itemsize)

Number of Dimensions: 1
Shape: (7,)
Size: 7
Data Type: float64
Item Size: 8


In [3]:
#Arithmetic operations using NumPy
#1. Addition
import numpy as np
a = np.array([30,20,10])
b = np.array([10,20,30])
result = np.add(a,b)
print(result)

[40 40 40]


In [5]:
#2. Substraction
a = np.array([[30,20,10],[50,70,90]])
b = np.array([[10,20,30],[40,30,50]])
result = np.subtract(a,b)
print(result)

[[ 20   0 -20]
 [ 10  40  40]]


In [7]:
#3. Multiplication
a = np.array([30,20,10])
b = np.array([10,20,30])
result = np.multiply(a,b)
print(result)

[300 400 300]


In [9]:
#4. Division
a = np.array([[30,20,10],[50,70,90]])
b = np.array([10,20,30])
result = np.divide(a,b)
print(result)

[[3.         1.         0.33333333]
 [5.         3.5        3.        ]]


In [11]:
#5. Power of
a = np.array([30,20,10])
b = np.array([10,20,30])
result = np.power(a,b)
print(result)

[ 716276736          0 1073741824]


In [36]:
#Statistical operations
#Calculating Median, Mean, Standard Deviation, and Variance in the array
array = np.array([[4,3,2],[10,1,0],[5,8,24]])
print(np.median(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))

4.0
6.333333333333333
6.944222218666553
48.22222222222222


In [16]:
#Calculating Percentiles
#The np.percentile() function is used to compute the nth percentile of the arrat elements. It should be between 0 and 100.
print(np.percentile(array, 85))

9.6


In [20]:
#String function in Numpy
s1 = np.array(["Hello","World"])
s2 = np.array(["Welcome","Learners"])
result = np.char.add(s1,s2)
print(result)

['HelloWelcome' 'WorldLearners']


In [22]:
s3 = "Hello how are you"
print(s3)
z = np.char.replace(s3, "Hello", "Hi")
print(z)

Hello how are you
Hi how are you


In [24]:
z1 = np.char.upper(z)
z2 = np.char.lower(z)
print(z1)
print(z2)

HI HOW ARE YOU
hi how are you


In [34]:
arrA = [15, 25, 35, 45, 55]
arrB = [5, 10, 15, 20, 25]
print(np.add(arrA, arrB))
print(np.subtract(arrA, arrB))
print(np.multiply(arrA, arrB))
print(np.divide(arrA, arrB))
print(np.power(arrA, arrB))

[20 35 50 65 80]
[10 15 20 25 30]
[  75  250  525  900 1375]
[3.         2.5        2.33333333 2.25       2.2       ]
[     759375  1977800241 -2091638453 -1924594607   447042167]


In [42]:
arrC = [12, 22, 32, 42, 52, 62, 72, 82, 92, 102]
print(np.mean(arrC))
print(np.median(arrC))
print(np.std(arrC))
print(np.var(arrC))

57.0
57.0
28.722813232690143
825.0


In [48]:
arrX = ['Hello', 'Data', 'Science', 'Class', 'Learners']
arrY = ['World', 'Analysis', 'is', 'Fun', '2023']
print(np.char.add(arrX, arrY))
arrX = np.char.upper(arrX)
print(arrX)
arr = np.char.replace(arrY, "Fun", "Boring")
print(arr)

['HelloWorld' 'DataAnalysis' 'Scienceis' 'ClassFun' 'Learners2023']
['HELLO' 'DATA' 'SCIENCE' 'CLASS' 'LEARNERS']
['World' 'Analysis' 'is' 'Boring' '2023']


In [54]:
#Access Elements in the 1D array
import numpy as np
array1d = np.array([1,2,3,4,5,6])
array2d = np.array([[1,2,3],[4,5,6]])
array3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array1d[3])

4


In [58]:
#Access elements in the 2d array
print(array2d[1,1])

5


In [62]:
#Access elemetns in the 3d array
print(array3d[1,1,0])

10


In [64]:
#Negative Indexing
print(array1d[-3])

4


In [68]:
#print the last element of the 2d array using negative indexing
print(array2d)
print(array2d[-1,-1])

[[1 2 3]
 [4 5 6]]
6


In [70]:
#print the last element of 3d array using negative indexing
print(array3d[-1,-1,-1])

12


In [92]:
arr1 = np.array([2,3,4,5,6,4,4,5,3,7])
print(arr1)
arr2 = np.array([[1,2,3,4],[5,6,7,8],[5,3,8,9]])
print(arr2)
arr3 = np.array([[[1,2,3],[2,3,4]],[[5,6,7],[8,7,9]]])
print(arr3)
print("1d array:",arr1[4])
print("2d array:", arr2[2,1])
print("3d array:", arr3[1,1,0])

[2 3 4 5 6 4 4 5 3 7]
[[1 2 3 4]
 [5 6 7 8]
 [5 3 8 9]]
[[[1 2 3]
  [2 3 4]]

 [[5 6 7]
  [8 7 9]]]
1d array: 6
2d array: 3
3d array: 8


In [100]:
print(np.add(arr1[4],arr2[2,1]))
print(np.subtract(arr1[4],arr2[2,1]))
print(np.multiply(arr1[4],arr2[2,1]))

9
3
18


#NumPy array slicing
1. In python, slicing refers to moving elements from one index to another

In [105]:
import numpy as np
Employee_rating = np.array([1,4,3,5,6,8,9,10,12])
print(Employee_rating[1:7])

[4 3 5 6 8 9]


In [109]:
#Slicing 2d array
Z = np.array([[11,22,33,44,55],[66,77,88,99,110]])
print(Z[0,2:3])

[33]


In [111]:
#Negative slicing
Neg_slice= np.array([13,34,58,69,44,56,45,54])
print(Neg_slice[:-1])

[13 34 58 69 44 56 45]


#Problem Statement:
Creating arrays for slicing:
Create a 1D NumPy array with at least 15 elements
Create a 2D NumPy array with a minimum of 4 rows and 5 columns
Create a 3D NumPy array with at least 2 matrices, each containing 3 rows and 4 columns
Slicing 1D arrays:
Perform and demonstrate different slices on the 1D array, explore it using step values
Slicing 2D arrays:
Slice rows and columns separately and in combination
arr3 = np.array([[[1,2,3,4],[4,5,6,7],[6,7,8,9]],[[4,5,6,7],[6,7,8,9],[9,10,11,12]]])
Slicing 3D arrays:
Perform slicing to access different matrices, rows within matrices, and elements within rows
Negative slicing:
Implement negative slicing on 1D, 2D, and 3D arrays
Compare the outcomes of negative slicing with positive slicing

In [9]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8]])
print(arr2)
arr3 = np.array([[[1,2,3,4],[4,5,6,7],[6,7,8,9]],[[4,5,6,7],[6,7,8,9],[9,10,11,12]]])
print(arr3)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 6  7  8  9]]

 [[ 4  5  6  7]
  [ 6  7  8  9]
  [ 9 10 11 12]]]


In [23]:
#1D array slicing
print(arr1[3:6])
print(arr1[2:12:2])

[4 5 6]
[ 3  5  7  9 11]


In [49]:
#2D array slicing
print("2D array:",arr2[1,2:3])

2D array: [4]


In [47]:
#3D array slicing
print("3D array:",arr3[1,2,1:2])

3D array: [10]


In [43]:
#negative slicing for 1d array
negative_slice1 = arr1[:-6]
print(negative_slice1)
#negative slicing for 2d array
negative_slice2 = arr2[-1, :-2]
print(negative_slice2)
#negative slicing for 3d array
negative_slice3 = arr3[-1, -2, -2:] 
print(negative_slice3)

[1 2 3 4 5 6 7 8 9]
[4 5 6]
[8 9]


Problem Statement:
You are working with a dataset in which each feature has different units and scales, which might affect the performance of your machine learning algorithm. Your task is to normalize the data so that each feature has a mean of 0 and a standard deviation of 1.

The dataset is a NumPy array with the following structure:
data = np.array([
[15, 2000, 10],
[20, 2200, 15],
[18, 2100, 12],
[25, 2300, 20],
[30, 2500, 25]
])
Write a Python code using NumPy to:
1. Normalize the dataset so that each feature (column) has a mean of 0 and a standard deviation of 1.
2. Verify the results by printing the mean and standard deviation of each column of the normalized data.
Expected Output:
1. The mean of each column after normalization should be approximately 0.
2. The standard deviation of each column after normalization should be 1.

In [102]:
import numpy as np
data = np.array([
[15, 2000, 10],
[20, 2200, 15],
[18, 2100, 12],
[25, 2300, 20],
[30, 2500, 25]
])
U = np.mean(data)
print("The  mean is:", U)
V = np.std(data)
print("The std is:", V)
norm = (data-U)/V
norm_mean = round(np.mean(norm))
norm_std = np.std(norm)

print("Normalized Data:", norm)

print("\nMean after normalization:", norm_mean)

print("\nStandard deviation after normalization:", norm_std)

The  mean is: 752.6666666666666
The std is: 1042.3166931834533
Normalized Data: [[-0.70771837  1.19669323 -0.71251537]
 [-0.70292136  1.38857349 -0.70771837]
 [-0.70484016  1.29263336 -0.71059657]
 [-0.69812435  1.48451363 -0.70292136]
 [-0.69332735  1.67639389 -0.69812435]]

Mean after normalization: 0

Standard deviation after normalization: 1.0


In [5]:
#Creating and accessing pandas using different methods
import pandas as pd
data = [4, 6, 8, 4, 8]
series = pd.Series(data)
print(series)
index = ['a','b','c','d','e']
series_with_index = pd.Series(data, index=index) # Changed to create a Series with the specified index
print(series_with_index)
d = {"a":1,"b":2,"c":4,"d":6}
series = pd.Series(d)
print(series)

0    4
1    6
2    8
3    4
4    8
dtype: int64
a    4
b    6
c    8
d    4
e    8
dtype: int64
a    1
b    2
c    4
d    6
dtype: int64


In [7]:
first_n_rows = series.head(3)
print(first_n_rows)
last_n_rows = series.tail(3)
print(last_n_rows)
stats = series.describe()
print(stats)
unique_value = series.unique()
print(unique_value)
sum_with_series = series + series_with_index
print(sum_with_series)

a    1
b    2
c    4
dtype: int64
b    2
c    4
d    6
dtype: int64
count    4.000000
mean     3.250000
std      2.217356
min      1.000000
25%      1.750000
50%      3.000000
75%      4.500000
max      6.000000
dtype: float64
[1 2 4 6]
a     5.0
b     8.0
c    12.0
d    10.0
e     NaN
dtype: float64


In [23]:
sum_series=series+series
print(sum_series)

a     5.0
b     8.0
c    12.0
d    10.0
e     NaN
dtype: float64
a     2
b     4
c     8
d    12
dtype: int64


In [27]:
square_series = series.apply(lambda x: x**2)
print(square_series)
s=series+series_with_index
null_values = s.isnull()
print(null_values)
fill_null_val = s.fillna(0)
print(fill_null_val)

a     1
b     4
c    16
d    36
dtype: int64
a    False
b    False
c    False
d    False
e     True
dtype: bool
a     5.0
b     8.0
c    12.0
d    10.0
e     0.0
dtype: float64


In [37]:
#Querying a Series
#select element greater than 10
greater = series[series<=10]
print(greater)

a    1
b    2
c    4
d    6
dtype: int64


sales_data = [120,150,130,170,160,180,140]
days_of_week = ['Monday','Tuesday','Wednesday','Thrusday','Friday','Saturday']

In [12]:
import pandas as pd
sales_data = [120,150,130,170,160,180,140]
sales = pd.Series(sales_data)
print(sales)
days_of_week = ['Monday','Tuesday','Wednesday','Thrusday','Friday','Saturday','Sunday']
daily_sales = pd.Series(sales_data, index = days_of_week)
print(daily_sales)

0    120
1    150
2    130
3    170
4    160
5    180
6    140
dtype: int64
Monday       120
Tuesday      150
Wednesday    130
Thrusday     170
Friday       160
Saturday     180
Sunday       140
dtype: int64


In [16]:
day1 = daily_sales['Friday']
print(day1)

160


In [30]:
#Calculate total sales of the week
total_sale = daily_sales.sum()
print(total_sale)

1050


In [56]:
#Identify the day with the highest and lowest sales
highest_sales = daily_sales.idxmax()  
lowest_sales = daily_sales.idxmin()  

print("Day with highest sales:", highest_sales)  
print("Day with lowest sales:", lowest_sales) 

Day with highest sales: Saturday
Day with lowest sales: Monday


In [28]:
#Average sales for the week
avg_sale = daily_sales.mean()
print(avg_sale)

150.0


In [54]:
diff_sale = (daily_sales != avg_sale)
print("This are days different from average:\n",diff_sale)

This are days different from average:
 Monday        True
Tuesday      False
Wednesday     True
Thrusday      True
Friday        True
Saturday      True
Sunday        True
dtype: bool
